<?php

namespace Zedstar16\MassiveEvent\tasks\async;

use pocketmine\scheduler\AsyncTask;
use Zedstar16\MassiveEvent\manager\EventManager;

class AsyncOrderingTask extends AsyncTask
{

    private string $json_encoded_data;

    private string $result;

    public function __construct(string $json_encoded_data){
        $this->json_encoded_data = $json_encoded_data;
    }



    /*
     *    for ($i = 0; $i < count(TeamHandler::TEAM_NAMES); $i++) {
                $team = $team_handler->getTeam($i);
                $data[] = [
                    "kills" => $team->kills,
                    "deaths" => $team->deaths
                ];
            }
     */
    public function onRun(): void
    {
        $data = json_decode($this->json_encoded_data, true);
        $kill_map = [];
        $kdr_map = [];
        foreach ($data as $teamID => $team_data){
            foreach ($team_data["kills"] as $username => $kills){
                $kill_map[$username] = $kills;
                $deaths = $team_data["deaths"][$username];
                $kdr_map[$username] = $kills/($deaths === 0 ? 1 : $deaths);
            }
        }
        arsort($kill_map);
        arsort($kdr_map);
        $this->result = json_encode([$kill_map, $kdr_map]);
    }

    public function onCompletion(): void
    {
        $data = json_decode($this->result, true);
        EventManager::$ordered_kills = $data[0];
        EventManager::$ordered_kdr = $data[1];
        parent::onCompletion(); // TODO: Change the autogenerated stub
    }
}